name: make

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.cpp'
      - '**.hpp'
  push:
    paths:
      - '**.cpp'
      - '**.hpp'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Clang 12
      uses: egor-tensin/setup-clang@v1
      with:
        version: 12
        platform: x64

    - name: Build project
      run: |
        make
